### ISSUE TITLE
Link to the online version of the project

### ISSUE THREAD

**Issue by kennedyowusu** [kennedyowusu/kennedyowusu.github.io#1]
The link to this project hosted on GitHub pages is given below

https://kennedyowusu.github.io/

**Comment by omarsalem7** [comment]
Hi @kennedyowusu 😊, 
# STATUS: APPROVED! 🥇 💯 

![giphy](https://media.giphy.com/media/n5VaQoW39Z9S0/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 🚀 
Congratulations! 🎉 

## Highlights
✅ Project has met all the technical aspects you needed for this project. Keep rocking! 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by kennedyowusu** [comment]
Thank you @omarsalem7
